apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cd-pipeline-run
spec:
  pipelineRef:
    name: cd-pipeline
  params:
    - name: repo-url
      value: https://github.com/bhawana234/devops-capstone-project.git
    - name: branch
      value: main
    - name: build-image
      value: us.icr.io/sn-labs-bhawanamh444/accounts:latest
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipelinerun-pvc
  serviceAccountName: pipeline
