<<<<<<< HEAD
=======
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  description: This task will echo the message.
  params:
    - name: message
      description: The message to echo
      type: string
  steps:
    - name: echo-message
      image: alpine:3
      command: [/bin/echo]
      args: ["$(params.message)"]

---
>>>>>>> c870ddd (added link task)
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine:3.17
      script: |
        #!/bin/sh
        rm -rf /workspace/source/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  workspaces:
    - name: source
  params:
    - name: image
      default: "python:3.9-slim"
    - name: args
      type: array
      default:
        - "--count"
        - "--max-complexity=10"
        - "--max-line-length=127"
        - "--statistics"
  steps:
    - name: lint
      image: $(params.image)
      workingDir: /workspace/source
      script: |
<<<<<<< HEAD
        #!/bin/sh
        pip install flake8
        flake8 "${params.args[@]}"
=======
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi
>>>>>>> c870ddd (added link task)
