apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine:3.17
      script: |
        #!/bin/sh
        rm -rf /workspace/source/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  workspaces:
    - name: source
  params:
    - name: image
      default: "python:3.9-slim"
    - name: args
      type: array
      default:
        - "--count"
        - "--max-complexity=10"
        - "--max-line-length=127"
        - "--statistics"
  steps:
    - name: lint
      image: $(params.image)
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        pip install flake8
        flake8 "${params.args[@]}"
